### ISSUE TITLE
Setup issues while setting drill when using 1.1.7 version

### ISSUE THREAD

**Issue by amoghrajesh** [JohnOmernik/sqlalchemy-drill#94]
Apache airflow is running into some compatibility issues when we installed and tried the new 1.1.7 version.

Error stack:
```
_________________ ERROR at setup of TestDrillHook.test_execute _________________
/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py:3371: in _wrap_pool_connect
    return fn()
/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py:382: in connect
    return _ConnectionFairy._checkout(self, self._fairy)
/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py:894: in _checkout
    fairy = _ConnectionRecord.checkout(pool)
/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py:493: in checkout
    rec = pool._do_get()
/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py:364: in _do_get
    c = self._create_connection()
/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py:273: in _create_connection
    return _ConnectionRecord(self)
/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py:388: in __init__
    self.__connect()
/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py:691: in __connect
    pool.logger.debug("Error on connect(): %s", e)
/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py:70: in __exit__
    compat.raise_(
/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py:211: in raise_
    raise exception
/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py:686: in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py:574: in connect
    return dialect.connect(*cargs, **cparams)
/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py:598: in connect
    return self.dbapi.connect(*cargs, **cparams)
E   AttributeError: 'NoneType' object has no attribute 'connect'

During handling of the above exception, another exception occurred:
providers/apache/drill/tests/integration/apache/drill/hooks/test_drill.py:38: in setup_method
    self.conn = DrillHook().get_conn()
providers/apache/drill/src/airflow/providers/apache/drill/hooks/drill.py:67: in get_conn
    return engine.raw_connection()
/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py:3404: in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py:3372: in _wrap_pool_connect
    except dialect.dbapi.Error as e:
E   AttributeError: 'NoneType' object has no attribute 'Error'
---------------------------- Captured stdout setup -----------------------------
```

Example CI failure: https://github.com/apache/airflow/actions/runs/13538699403/job/37835922042

**Comment by amoghrajesh** [comment]
Some more details about our integration tests.

Docker compose:
```
services:
  drill:
    container_name: drill
    image: "apache/drill:1.21.1-openjdk-17"
    labels:
      breeze.description: "Integration required for drill operator and hook."
    volumes:
      - drill-db-volume:/data
      - ./drill/drill-override.conf:/opt/drill/conf/drill-override.conf
    restart: "on-failure"
    ports:
      - "${DRILL_HOST_PORT}:8047"
    stdin_open: true
  airflow:
    depends_on:
      - drill
    environment:
      - INTEGRATION_DRILL=true
volumes:
  drill-db-volume:
```


Test:
```
import os
import socket
from decimal import Decimal

import pytest

from airflow.providers.apache.drill.hooks.drill import DrillHook

AIRFLOW_CONN_DRILL_DEFAULT = "drill://{hostname}:8047"
TEST_TABLE_ID = "dfs.tmp.test_airflow"


@pytest.mark.integration("drill")
class TestDrillHook:
    def setup_method(self):
        os.environ["AIRFLOW_CONN_DRILL_DEFAULT"] = AIRFLOW_CONN_DRILL_DEFAULT.format(
            hostname=socket.gethostbyname("drill")
        )
        self.conn = DrillHook().get_conn()
        self.cursor = self.conn.cursor()
        sql = f"""
        create table {TEST_TABLE_ID} as
        select * from cp.`employee.json` limit 10
        """
        self.cursor.execute(sql)

    def teardown_method(self):
        self.cursor.execute(f"DROP TABLE {TEST_TABLE_ID}")
        self.conn.close()

    def test_execute(self):
        sql = f"select * from {TEST_TABLE_ID} limit 10"
        self.cursor.execute(sql)
        row = self.cursor.fetchone()
        assert row == (
            1,
            "Sheri Nowmer",
            "Sheri",
            "Nowmer",
            1,
            "President",
            0,
            1,
            "1961-08-26",
            "1994-12-01 00:00:00.0",
            Decimal("80000.0"),
            0,
            "Graduate Degree",
            "S",
            "F",
            "Senior Management",
            None,
        )

```
